routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/reports', function () {
    return view('report');
})->middleware('admin.auth');

Route::post('/pdf', "ExportController@pdf")->middleware('admin.auth');
Route::post('/excel', "ExportController@excel")->middleware('admin.auth');

Route::group(['prefix' => 'admin'], function () {
    VoyagerExtension::routes();
});

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('super.auth');

app/Transaction.php
<?php

namespace App;

use Carbon\Carbon;
use App\Traits\TimeZone;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Transaction extends Model
{
    use TimeZone;
    protected $fillable = [
        'amount',
        'amount_egp',
        'exchange_rate',
        'currency_id',
        'company_id',
        'account_id',
        'worker_id',
        'notes',
        'direction',
        'attachments',
    ];

    public function currency(): BelongsTo
    {
        return $this->belongsTo(Currency::class);
    }
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }
    public function worker(): BelongsTo
    {
        return $this->belongsTo(Worker::class);
    }
    public function account(): BelongsTo
    {
        return $this->belongsTo(Account::class);
    }
    public function getCreatedAtAttribute($value){
        return $this->shiftDate($value);
    }
    
    public function transactionFiles(): HasMany
    {
        return $this->hasMany(TransactionFile::class);
    }
    public function getAttachmentsAttribute($value){
        if(!$value && !$this->transactionFiles->first()){
            return null;
        }

        if(!$value){
            $link = $this->CreateAttachments();
            $this->update(['attachments' => $link]);

            return $this->fileParser($link);
        }

        return $this->fileParser($value);
    }

    public function CreateAttachments(){
        $files = array();
        $folder_name = 'folder_'.$this->id."_".Carbon::now()->format('h_i_s');
        $zip_name = 'zip_'.$this->id."_".Carbon::now()->format('h_i_s').".zip";
        mkdir(storage_path('app/public')."/"."GraphQL/files/".$folder_name , 0775);
        
        foreach ($this->transactionFiles as $transactionFile){
            $links = explode("/",$transactionFile->file_link);
            $file_link = end($links);
            
            rename(storage_path('app/public')."/".$transactionFile->file_link, storage_path('app/public')."/"."GraphQL/files/".$folder_name."/".$file_link);
            $transactionFile->update(["file_link" => "GraphQL/files/".$folder_name."/".$file_link]);
        }
        $zipper = new \Madnest\Madzipper\Madzipper;
        $zip = $zipper->make(storage_path('app/public')."/zip_files".'/'.$zip_name)->add(storage_path('app/public').'/GraphQL/files/'.$folder_name)->close();
        return "zip_files/".$zip_name;
    }

    public function fileParser($value){
        if ($value == null) {
            return $value;
        }
        if (!request()->is('graphql')) {
            $meta_data = new \stdClass;
            $meta_data->download_link = $value;
            $meta_data->original_name = 'Download Attachments';
            $value = array();
            $value[0] = $meta_data;
            return json_encode($value);
        }

        return asset('storage/' . $value);
    }
}

resources/views/export.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        
        <style>
            td{
                width:20%;
            }
            html{
                background-color: #fff;
                color: #636b6f;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }
            body{
                font-family: Helvetica;
            }
            /* Table Styles */

            .head-wrapper{
                margin: 50px 70px 50px;
                font-size:12px;
                font-weight: bold;
            }
            .highlight{
                font-weight: normal;
            }
            .table-wrapper{
                margin: 10px 70px 70px;
            }

            .fl-table {
                border-radius: 5px;
                font-size: 12px;
                font-weight: normal;
                border: none;
                border-collapse: collapse;
                width: 100%;
                max-width: 100%;
                white-space: nowrap;
                background-color: white;
            }

            .fl-table td, .fl-table th {
                text-align: center;
                padding: 8px;
            }

            .fl-table td {
                border-right: 1px solid #f8f8f8;
                font-size: 12px;
            }

            .fl-table thead th {
                color: #ffffff;
                background: #4FC3A1;
            }


            .fl-table thead th:nth-child(odd) {
                color: #ffffff;
                background: #324960;
            }

            .fl-table tr:nth-child(even) {
                background: #F8F8F8;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="content">
                <h1 style="text-align:center">Financial Report</h1>
                <div class="head-wrapper">
                    <p><span class="highlight">Report From:</span>  {{$from}} <span class="highlight"> &emsp; To:</span> {{$to}}</p>
                    <p><span class="highlight">Issued By:</span> {{$name}}</p>
                    <p><span class="highlight">Date and Time:</span> {{$now}}</p>
                </div>
                <div id="exportpdf" class="table-wrapper">
                    <table class="fl-table">
                        <thead>
                        <tr>
                            <th>Amount</th>
                            <th>Currency</th>
                            <th>Company</th>
                            <th>Account</th>
                            <th>Worker</th>
                            <th>Exchange Rate</th>
                            <th>Amount (EGP)</th>
                            <th>Creation Date</th>
                        </tr>
                        </thead>
                        <tbody id="transactions">
                            @foreach($data as $transaction)
                                <tr>
                                    <td>{{number_format($transaction->amount, 2)}}</td>
                                    <td>{{$transaction->currency->name}}</td>
                                    <td>{{$transaction->company->name}}</td>
                                    <td>{{$transaction->account->name}}</td>
                                    <td>{{$transaction->worker->name}}</td>
                                    <td>{{number_format($transaction->exchange_rate, 2)}}</td>
                                    @if($transaction->direction == "out")
                                        <td style="color:red;">-{{number_format($transaction->amount_egp, 2)}}</td>
                                    @else
                                        <td style="color:green;">{{number_format($transaction->amount_egp, 2)}}</td>
                                    @endif
                                    <td>{{$transaction->created_at}}</td>
                                </tr>
                            @endforeach
                        <tbody>
                    </table>
                </div>
                <div id="exportpdf_2" class="table-wrapper">
                    <table class="fl-table">
                        <tr> 
                            <td colspan="4" style="background-color:#4FC3A1; font-size:15px; color:white;"> Total: </td>
                            <td colspan="4" style="background-color:#324960; font-size:15px; color:white;">{{$total}} (EGP)</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>